### ISSUE TITLE
关于超时计算和暴露调用的方式的想法

### ISSUE THREAD

**Issue by sodawy** [shimohq/yato#12]
关于超时计算，我的一个实现想法。在执行`executeCommand `时，仅收集启动时间和命令ID，去掉`setTimeout`计算超时。而且`bucketList`中，设置`setInterval`，一次计算多个`bucket`，用当前时间做减法计算超时。优点如下：
- 性能：省掉每个`executeCommand`中的`timer`消耗，延时放在`bucketList-setInterval`一起计算。通常运行的命令大于80%的情况是正常的，少量是超时的，让每个任务都的超时验证，不如粘在一起做划算。
- 时间更准确：计算是否超时时，是取启动和结束（或超时）两次系统时间(详见下面)，与setInterval是否被主线程延迟无关。

----

关于暴露调用的方式。我比较倾向[yammer/circuit-breaker-js](https://github.com/yammer/circuit-breaker-js)的。**把成功和失败的`function`返回给使用者，让他们自己决定调用时机和位置**。这样更加灵活和易扩展。
- 我从一开始就在想，如何把yato结合到koa。一个req在koa中可能要经历路由和许多中间件逻辑，目前的方式，我们只能在外层把整个req过程包起来，缺乏灵活；而如果让用户自己决定啥时候算成败会更好一些
- 结束时间会更加准确。

----

改动不小，欢迎探讨。

----

最后感谢作者建了思路这么好的库，我之前做的系统也是大量依赖第三方接口，经常莫名抽风=。=，当时视野有限，没想当这么好的断路器思路，再次感谢。

**Comment by leverz** [comment]
使用 `setTimeout` 是为了防止一直处于等待响应的状况，我们想要达到的效果是，如果超时立刻响应失败，而不再继续等待。这里确实有消耗，你有什么更好的办法么？

至于 `setInterval`，在最新的版本里已经被去掉了，改为你说的那种用计算时间的方式生成 bucket 。可以看下这里 https://github.com/shimohq/yato/issues/9

关于你说的暴露调用的方式，我没太理解 【把成功和失败的 `function` 返回给使用者，让他们自己决定调用时机和位置】是什么意思？

**Comment by sodawy** [comment]
可能我理解的不太一致。我觉得一种可行`yato`在`koa webserver`中的使用方式是类似这样的：

```js
const koa = reuqire('koa');
const Yato = require('yato');

const app = new koa();
const yato = new Yato();

app.use(async (ctx, next) => {
   const { stats, success, fail } = yato.start(ctx.path);

   if(stats == 'OPEN'){
       ctx.body = 'yato breaker';
       ctx.status = 500;
       return;  //不再继续后面的中间件逻辑
   }

   await next;

   ctx.isSuccess ? success() : fail(); //success和fail包含bucket id，以找到对应的开始时间做减法&计数
});
```

他是对http server可用性和访问速度的一种保护。request穿过yato切面，根据之前请求的统计得出的stats，open的话走failFunction，close的话啥也不干仅统计。request在整个server中的逻辑，yato不干涉执行、超时等逻辑，这些由server自己处理，我们仅采集数据，调整stats。

我是不是越走越远了。。如果理解不一致，我后面的计时方案，也是不成立的。

**Comment by leverz** [comment]
嗯嗯，明白了，你是希望能更灵活一点，把控制权交给外部。

我觉得 Yato 已经给外部足够的自由度了，它只是执行了你交给它的 command，command 本身的执行结果并不会改变，即 Yato 只是控制了 command 是否执行。Yato 只是想在 command 之上做一层保护，至于其他时候，该怎样就怎样，有 Yato 和没有 Yato ，在调用命令时不应该有任何差别。

就像你举的例子，其实可以这么写：

```JavaScript
const Koa = reuqire('koa')
const Yato = require('yato')

const app = new Koa()
const yato = new Yato()

app.use(async (ctx, next) => {
  try {
    await yato.run(next)
  } catch (error) {
    if (yato.isOpen()) {
      ctx.body = 'yato breaker'
      ctx.status = 500
      return
    }
    ctx.isSuccess = false
  }
})
```

如果你想把 `ctx.isSuccess === false` 当成失败来处理的话，可以在程序中抛出错误，最后在这个中间件的 catch 里做一下处理。

**Comment by sodawy** [comment]
还是在koa的语境下，如果接口出了问题，你会用yato来接收抛出的exception还是webserver自己的业务代码来处理呢？而且很多时候，出错或者超时，并不会抛exception或者回reject，就在某个环节res.end()了，next也正常走，这样按你的代码，yato却记作成功了。

我很认同你说的无感，让业务保有自己的逻辑。就是有yato可以跑，去掉yato切面也可以跑。但如果按照你的代码，yato的插拔就跟业务有了藕合。yato帮业务接收了异常、做了超时监听。业务要适应yato，失败了需要throw或reject；还要考虑超时了，会跳到yato会throw error出来，而不是自己的超时逻辑。

既然两位作者，都对目前的这种方式满意，我也就不再磨叨了：）

**Comment by leverz** [comment]
其实 Yato 的设计初衷是被用在客户端的，也就是服务的调用方。你所说的场景我也会好好考虑下是否合适。

也十分感谢你提醒我们 Yato 还可以做更多的事情。

**Comment by sodawy** [comment]
我开始思路也不是很清楚，所以有点车轱辘。也很高兴与你交流
