### ISSUE TITLE
懒生成 bucket 以确保精确

### ISSUE THREAD

**Issue by luin** [shimohq/yato#9]
目前使用的 setInterval 方式定时生成 bucket 有两个主要缺点：

1. 不精准。Node.js 中 setInterval 的误差量级在几十 ms 左右，与 `windowDuration` 的通常取值可比；
2. 消耗系统资源。setInterval 相对底层，如果数量非常多的话对系统资源会有一定消耗。

对于「不精准」的另一个补充是，setInterval 会被系统忙事件阻塞，从而造成生成的 bucket 数量逐渐误差越来越明显。参考如下代码：

```javascript
let i = 0
let start = Date.now()
setInterval(() => {
  i += 1
  console.log((Date.now() - start) / 1000, i)

  if (i === 5) {
    // 模拟系统阻塞
    while (Date.now() - start < 8000) {
    }
  }
}, 1000)
```

生成结果是：

```
1.016 1
2.022 2
3.022 3
4.025 4
5.026 5
9.004 6
10.008 7
11.013 8
12.016 9
13.02 10
```

能想到的一个改进方案是获取 currentBucket 或者计算统计结果时懒生成 bucket。

**Comment by leverz** [comment]
这种方式确实消耗系统资源，但是对于「不精准」我觉得是在可接受范围内的。我们期望在下一个 bucket 生成之前，所有的命令的执行结果都被统计在当前的 bucket 中，至于这个 bucket 中应该记录执行多少次命令是未知的，也可以理解成是随机的。

根据你的改进方案，我觉得可以在每次命令执行完毕，要写入 bucket 时，计算一下现在到上次生成 bucket 的时间，超过指定时间，就再生成一个。

**Comment by luin** [comment]
嗯嗯对，超过指定时间就生成一个（如果时间比较久就是多个）。因为做统计时会依赖一个 bucket 的时间是固定的

**Comment by leverz** [comment]
cool，我来改改这里吧！
